num = int(input('Digite qualquer número de 0 a 9999:'))
n = str(num)
print('a unidade é {}'.format(n[3]))
print('a dezena é {}'.format(n[2]))
print('a centena é {}' .format(n[1]))
print('o milhar é {}' .format(n[0]))
